fix(KUI-1140): periods has been removed from courseLink
KTH/kopps-public-react-web pull request #255
Opened 2024-06-12 14:54 UTC by amirhossein-haerian

We have removed periods from course link, and we could not find any other logic associated with retrieving this parameter to be removed.

2024-06-13 07:28 UTC, karlandindrakryggen approved these changes

2024-06-13 09:39 UTC, belanglos requested changes
I suggest that we get rid of the `startSign`-logic as well. Now that we have only one queryparam we don't need it anymore.

2024-06-13 09:39 UTC, belanglos commented on public/js/app/util/links.js
> +  const startSign = term !== undefined && term !== '' ? '?' : ''
```suggestion
```

2024-06-13 09:39 UTC, belanglos commented on public/js/app/util/links.js
>    const startTerm = term !== undefined && term !== '' ? `startterm=${term}` : ''
```suggestion
  const startTerm = term !== undefined && term !== '' ? `?startterm=${term}` : ''
```

2024-06-13 09:39 UTC, belanglos commented on public/js/app/util/links.js
> +  const startSign = term !== undefined && term !== '' ? '?' : ''
Because we now only have one possible query parameter, we can just prepend the `startSign` before `startterm`.

2024-06-13 09:39 UTC, belanglos commented on public/js/app/util/links.js
> +  return pageLink(`/student/kurser/kurs/${courseCode}${startSign}${startTerm}`, language) // outside link
```suggestion
  return pageLink(`/student/kurser/kurs/${courseCode}${startTerm}`, language) // outside link
```

2024-06-14 09:35 UTC, amirhossein-haerian commented on public/js/app/util/links.js
>    const startTerm = term !== undefined && term !== '' ? `startterm=${term}` : ''
now we have removed the logic for startSign and we hae added the questionMark before "startterm".

2024-06-17 06:02 UTC, belanglos approved these changes
LGTM! 🏅

2024-06-17 06:39 UTC, axelbjo approved these changes

2024-06-17 11:23 UTC, merged