fix(KP-327): clearing unnecessary environment variables inside .env.in
KTH/kopps-public-react-web pull request #256
Opened 2024-06-14 06:21 UTC by amirhossein-haerian

2024-06-14 12:57 UTC, karlandindrakryggen requested changes

2024-06-14 12:57 UTC, karlandindrakryggen commented on config/serverSettings.js
> +const devServicePublish = '/student/kurser'
I think that if this is named **dev**ServicePublish it should also be wrapped in devDefaults.

So this should be changed to
```suggestion
const devServicePublish = devDefaults( '/student/kurser')
```
or  remove **dev** if its not supposed to be dev only(maybe call it `servicePublish` or `defaultServicePublish`)
```suggestion
const servicePublish = '/student/kurser'
```

2024-06-17 05:19 UTC, karlandindrakryggen approved these changes

2024-06-17 06:10 UTC, belanglos approved these changes
LGTM!

2024-06-17 10:38 UTC, axelbjo approved these changes

2024-06-17 11:23 UTC, merged