refactor(KP-330): Typescript setup
KTH/kopps-public-react-web pull request #266
Opened 2024-06-26 13:12 UTC by axelbjo

2024-06-26 13:17 UTC, amirhossein-haerian approved these changes
LGTM 🚀

2024-06-27 14:27 UTC, belanglos commented
Great job! Really happy about this 🚀 😃

2024-07-22 14:02 UTC, karlandindrakryggen requested changes
I think you should fix the problem with `noImplicitAny`, probably by adding `allowJs`.

I guess you normally could skip `ourDir` when using it with webpack, but I got an warning about it when using `allowJs` because the default is to ourput in same dir (that would cause js files to be overwritten by its own output). So I would say that we can keep outDir even if its not used.

2024-07-23 11:45 UTC, axelbjo commented on webpack.config.js
> +          test: /\.tsx?$/,
We have updated it so it handles .ts and .tsx files now

2024-07-23 11:46 UTC, axelbjo commented on public/tsconfig.json
> +    "noImplicitAny": true,
"allowJs": true and "checkJs": false have been added to tsconfig.json now

2024-07-23 12:51 UTC, karlandindrakryggen approved these changes

2024-07-24 08:35 UTC, merged