fix(KP-343): basic search functionality is now implemented
KTH/kopps-public-react-web pull request #269
Opened 2024-08-05 13:56 UTC by amirhossein-haerian

2024-08-05 14:05 UTC, amirhossein-haerian commented on public/js/app/pages/NewSearchLandingPage.tsx
> +    window.location.href = newUrl
There are two reasons for using window.location.href instead of navigate form react-router-dom. 
1. we are trying to move all the links from app to www which by using window.location.href we can do that.
2.  right now query parameters are being get from server side so, it needs to be refreshed that we can get the data from mobx store. the other approach is to get the query parameters from front-end. I would be thankful to know your thoughts regarding this. (I think changes regarding this can be done in the next task for the filtes)

2024-08-06 08:05 UTC, karlandindrakryggen requested changes

2024-08-06 08:05 UTC, karlandindrakryggen commented on public/js/app/pages/NewSearchLandingPage.tsx
> +    window.location.href = newUrl
Lets talk more about this, but in short my opinion is
1. Yes we are trying to use www instead of app, but I would like us to have a minimum of extra logic for this. So i think its more than okey to stay on app.* here if you started on app*. 
2. But is this solution really refreshing the page from the server now? Maybe you solve this by sharing store? Lets discuss this further. I think it would be great if a full page refresh from server isn't needed.

One helper from `react-router` that can be used instead of navigate to set query params is [useSearchParams](https://reactrouter.com/en/main/hooks/use-search-params)

2024-08-06 08:22 UTC, karlandindrakryggen commented on public/js/app/pages/NewSearchLandingPage.tsx
> +    window.location.href = newUrl
update: setSearchParams from useSearchParams isn't right as we want to change path as well

2024-08-07 06:41 UTC, amirhossein-haerian commented on public/js/app/pages/NewSearchLandingPage.tsx
> +    window.location.href = newUrl
Thanks for your points,
Since there is no need to refresh the page for updating the store anymore, in the latest changes I used "useNavigate" from "react-router-dom" to change both path and search parameters.

2024-08-07 06:42 UTC, amirhossein-haerian commented on public/js/app/util/newSeachApi.ts
> +import axios, { AxiosResponse } from 'axios'
I agree with you, In the latest changes the fetch() functionality has been replaced with "axios" 3rd party library functionality.

2024-08-07 06:48 UTC, amirhossein-haerian commented on public/js/app/app.jsx
> +  const newSearchStore = _initStore({ storeId: 'newSearchPage' })
In the latest changes in the code the "applicationStore" is removed as a component parameter and the creation of the store is moved to the Wrapper components using the "initCallback" (which now is called "initApplicationStoreCallback"). This reduced the amount of _initCalls to only the necessary calls for each page that we are actually visiting.

To have a shared store for two different pages we need to have exactly the same "initApplicationStoreCallback", for that reason "sharedInitApplicationStoreCallback" is now introduced to save the shared "initApplicationStoreCallback"s.

2024-08-07 06:57 UTC, amirhossein-haerian commented on public/js/app/pages/NewSearchPage.tsx
> +          ({course, searchHitInterval}) => (<p key={course.courseCode}><b>{course.title}</b> {course.courseCode} - {formatShortTerm(searchHitInterval.startTerm, language)}</p>)
Since we have two types of results, for those results that we have the "startPeriod" and "endPeriod" the key is now a combination of the courseCode, startPeriod, and endPeriod. It can be a temporary solution until we find a proper value for key.

2024-08-07 06:59 UTC, amirhossein-haerian commented on public/js/app/hooks/newSearchUseAsync.tsx
Thanks for the valuable points, the required changes is done now.

2024-08-07 07:58 UTC, amirhossein-haerian commented
In the latest changes the unnecessary useEffect is removed from the wrapper components and also the unnecessary usage of initApplicationStore is now removed.

2024-08-07 13:08 UTC, karlandindrakryggen approved these changes
Great job! 

One more small thing to change at this point, see the new comment below about <a> tag, then its good to merge!

2024-08-07 13:08 UTC, karlandindrakryggen commented on public/js/app/components/SearchFilters.tsx
> +        <a onClick={handleBackButton} className="kth-button back">
```suggestion
        <Link to={ancestorItem.href} className="kth-button back">{ancestorItem.label}</Link>
```
An `<a>` tag needs a href prop to be valid (for accessibility reasons etc). I guess you switched to onclick to prevent page from reloading from server? 

One solution for this would be to keep the `href` and the add `onClick` with preventDefault as an enhancement, but the good thing is that react router already has a [Link](https://reactrouter.com/en/main/components/link) component for that. So just replace `<a href= ...>` with `<Link to=...>` instead and an a tag with both href and onclick with nagivate will be insterted.

2024-08-07 13:11 UTC, amirhossein-haerian commented on public/js/app/components/SearchFilters.tsx
> +        <a onClick={handleBackButton} className="kth-button back">
Very good point, I will use Link from react-router-dom for sure 🙌

2024-08-07 17:09 UTC, merged