feat(KP-373): replace the old search with the newer version
KTH/kopps-public-react-web pull request #299
Opened 2024-10-21 13:49 UTC by amirhossein-haerian

In this commit the old search and all of the dependencies are removed now.

2024-10-21 14:41 UTC, axelbjo approved these changes
Looks good to me! I tried running this on my machine as well and it seems to work fine.

2024-10-22 06:37 UTC, karlandindrakryggen reviewed
Find some files/components/strings with the word "newSearch..." still. 

Both `searchHelper.js` and `newSearchHelper.ts` still exists. Remove the first one, and rename the second to just searchHelper.ts? 

And see more places in comments:

2024-10-22 06:37 UTC, karlandindrakryggen commented on public/js/app/pages/SearchLandingPage.tsx
The component is still called `NewSearchLandingPage` internally here.

2024-10-22 06:37 UTC, karlandindrakryggen commented on public/js/app/pages/SearchPage.tsx
The component is still called `NewSearchPage` internally here.

2024-10-22 06:37 UTC, karlandindrakryggen commented on server/server.js
> +  SearchPage.searchThirdCycleCourses
Some "newSearch..." left here to rename:
- public.newSearchAllCourses
- public.newSearchAllCoursesResult
- public.NewSearchThirdCycleCourses
- public.NewSearchThirdCycleCoursesResult

2024-10-22 06:50 UTC, karlandindrakryggen requested changes
Looks great! Some renaming left (see previous comment) and a small possible cleanup in koppsApi.js.

2024-10-22 06:50 UTC, karlandindrakryggen commented on server/controllers/searchCtrl.js
> -    log.debug(` performCourseSearch with ${searchParamsStr} response: `, apiResponse)
`getSearchResults` is only used here, so it could be remove from `koppsApi.js` now.

2024-10-22 07:47 UTC, amirhossein-haerian commented
> Looks great! Some renaming left (see previous comment) and a small possible cleanup in koppsApi.js.

Thanks for checking the files and for your great comments, now I made the required changes and updated the code.

2024-10-22 07:53 UTC, karlandindrakryggen approved these changes

2024-10-22 07:54 UTC, merged